apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: artist-relations-team
  description: The artist relation team
spec:
  type: team
  profile:
    displayName: Artist Realtions
    email: artistrelations@example.com
  children: []
  members: [jdoe]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - component:default/artist-web-lookup
  providesApis:
    - artist-api