apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shop
  description: Everything about sysco shop
spec:
  owner: sysco-shop-team
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shop-ordering
  description: Everything about sysco shop ordering
spec:
  owner: sysco-shop-ordering-team
  subdomainOf: shop
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shop-users-accounts
  description: Everything about sysco shop users and accounts
spec:
  owner: sysco-shop-users-accounts-team
  subdomainOf: shop
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shop-accounts-onboarding
  description: Everything about sysco shop accounts onboarding
spec:
  owner: sysco-shop-accounts-onboarding-team
  subdomainOf: shop-users-accounts 
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shop-authentication
  description: Everything about sysco shop authentication
spec:
  owner: sysco-shop-authentication-team
  subdomainOf: shop-users-accounts
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jb
spec:
  profile:
    displayName: Jonathan Black
    email: jb@sysco.com
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sasin
spec:
  profile:
    displayName: Sasitha Niranjana
    email: sasitha.n@sysco.com
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: shanik
spec:
  profile:
    displayName: Shanik Makalanda
    email: shanik.m@sysco.com
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: laya
spec:
  profile:
    displayName: Layansan
    email: laya@sysco.com
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: chandima
spec:
  profile:
    displayName: Chandima
    email: chandima@sysco.com
  memberOf: []           
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sysco-shop-team
  description: The team responsible of the design, development of sysco shop
spec:
  type: team
  profile:
    displayName: Team Sysco Shop
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sysco-shop-ordering-team
  description: The team responsible of the design, development of sysco shop ordering
spec:
  type: team
  profile:
    displayName: Team Sysco Shop Ordering
  parent: sysco-shop-team  
  children: []
  members: [jb,chandima]  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sysco-shop-users-accounts-team
  description: The team responsible of the design, development of sysco shop users and accounts
spec:
  type: team
  profile:
    displayName: Team Sysco Shop Users & Accounts
  parent: sysco-shop-team  
  children: [] 
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sysco-shop-accounts-onboarding-team
  description: The team responsible of the design, development of sysco shop users and accounts Onboarding
spec:
  type: team
  profile:
    displayName: Team Sysco Shop Users & Accounts Onboarding
  parent: sysco-shop-users-accounts-team
  children: []
  members: [sasin]  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sysco-shop-authentication-team
  description: The team responsible of the design, development of sysco shop users and accounts Authentication
spec:
  type: team
  profile:
    displayName: Team Sysco Shop Users & Accounts Authentication
  parent: sysco-shop-users-accounts-team
  children: []
  members: [laya,shanik]       
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-permission-management-portal
  description: Unified system to manage user permissions to sysco shop
spec:
  owner: sysco-shop-authentication-team
  domain: shop-authentication
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-authentication-system
  description: System for user authentication and issue JWT tokens
spec:
  owner: sysco-shop-authentication-team
  domain: shop-authentication  
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: keycloak
  description: Keycloak IDP
spec:
  type: identity-provider
  owner: sysco-shop-authentication-team
  system: user-authentication-system
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: sysco-shop-authentication-team
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
  description: The service to handle user authentication
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: sysco-shop-authentication-team
  system: user-authentication-system
  dependsOn:
    - resource:default/keycloak
  providesApis:
    - petstore